### ISSUE TITLE
Details provided by extension only load after refreshing the game panel once

### ISSUE THREAD

**Issue by tupaschoal** [thamara/improved-bga-game-info-extension#1]
I just installed the extension (tip https://github.com/thamara/improved-bga-game-info-extension/commit/ba7dbcaa564406e515c62f412e2efc04aa31e3a3) and went to try it out. Somehow the details it adds only appear after refreshing the game page once, as shown on the gif below:

![bug_chrome](https://user-images.githubusercontent.com/6443427/135365093-53af1470-f735-4d84-a57b-86000710f7a1.gif)

If I return to BGA's homepage and go into the same game again after this gif, the bug occurs again, consistently.

**Comment by thamara** [comment]
Were you running other browsers? Or more than one window of chrome?

**Comment by tupaschoal** [comment]
Just one browser for sure, but I don't remember if it had multiple windows (probably not)

**Comment by thamara** [comment]
I thought I have fixed it, at least I could not reproduce it unless if I have edge or firefox also open, which is really weird.
But I'll try again later.

**Comment by tupaschoal** [comment]
Happens consistently on Chrome (only web browser open) with just one tab!

**Comment by thamara** [comment]
Thanks for confirming. I'll try to look at it.

**Comment by thamara** [comment]
I expect this to be fixed now.
The issue was that BGA uses something (which I don't know the name, nor I can explain it well) that going from some pages to the game information page is not counted as "new page", and the script was being added only on such "new page" events.
Now I'm listening to those push changes and run the script.

**Comment by tupaschoal** [comment]
Tested it here and seems like it's solved now :)

**Comment by thamara** [comment]
Yay! Thanks!
